#!/usr/bin/env bash


GIT=`which git`
DIR="$HOME/.gwm"

# Add .gwm dir
#
if [[ -d "${DIR}" && ! -L "${DIR}" ]] ; then
    echo "Already installed!"
else
    cd $HOME
    $GIT clone https://github.com/adamar/gwm.git
    mv "$HOME/gwm" "$HOME/.gwm"
    touch "$HOME/.gwm/state/paths.bash"
fi


# Create Paths file
#
touch "$HOME/.gwm/state/paths.bash"


# Add line to profile
#
if grep -q "gwm installed" ~/.bashrc
then
    echo "Already added to .bashrc"
else
    echo 'source ~/.gwm/scripts/startsubshell #gwm installed' >> ~/.bashrc
fi


# Add GWM to Path
#
if grep -q "gwm added to path" ~/.bashrc
then
  echo "Already added to gwm to path"
else
  chmod u+x ~/.gwm/bin/gwm
  echo 'PATH=$PATH:~/.gwm/bin #gwm added to path' >> ~/.bashrc
fi


# Reload Bashrc
#
source ~/.bashrc


# Touch paths file
#
touch ~/.gwm/state/paths.bash


