#!/usr/bin/env bash


GIT=`which git`
DIR="${HOME}/.gwm"

# Add .gwm dir
#
if [[ -d "${DIR}" && ! -L "${DIR}" ]] ; then
    echo "Already installed!"
else
    cd $HOME
    $GIT clone https://github.com/adamar/gwm.git
    mv "${HOME}/gwm" "${HOME}/.gwm"
    touch "${HOME}/.gwm/state/paths.bash"
fi


# Create Paths file
#
touch "${HOME}/.gwm/state/paths.bash"


# Add line to profile
#
if grep -q "gwm installed" "${HOME}/.bashrc"
then
    echo "Already added to .bashrc"
else
    echo "source ${HOME}/.gwm/scripts/startsubshell #gwm installed" >> "${HOME}/.bashrc"
fi


# Add GWM to Path
#
if grep -q "gwm added to path" "${HOME}/.bashrc"
then
  echo "Already added to gwm to path"
else
  chmod u+x "${HOME}/.gwm/bin/gwm"
  echo "PATH=${PATH}:${HOME}/.gwm/bin #gwm added to path" >> "${HOME}/.bashrc
fi


# Reload Bashrc
#
source "${HOME}/.bashrc"


# Touch paths file
#
touch "${HOME}/.gwm/state/paths.bash"



